### ISSUE TITLE
User can search for entries

### ISSUE THREAD

**Issue by nsturz** [nsturz/My-Hyrule-Compendium#1]
## 📐 User can search for an entry on the Hyrule Compendium database API

> ##### By clicking the text field, the user will be able to search for information on almost anything in the _Breath Of The Wild_ world that falls under any of the following categories: 

- Creatures
- Equipment
- Materials
- Monsters
- Treasure

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when this issue is complete:

<img width="680" alt="Screen Shot 2022-08-01 at 5 45 14 PM" src="https://user-images.githubusercontent.com/94485412/182727724-a19bde40-7742-422f-8efa-d6c3510c7304.png">

<img width="692" alt="Screen Shot 2022-08-03 at 7 55 40 PM" src="https://user-images.githubusercontent.com/94485412/182753274-a7a1c448-2d84-41c8-a0e9-ec6bd5be30cd.png">

<img width="275" alt="Screen Shot 2022-08-01 at 5 45 58 PM" src="https://user-images.githubusercontent.com/94485412/182727756-889f0b6a-0d24-4f7e-b0e8-6bb8c767e4e4.png">

<img width="266" alt="Screen Shot 2022-08-03 at 4 06 32 PM" src="https://user-images.githubusercontent.com/94485412/182727780-07d2847c-6a52-4f5d-88c3-00d71a7cd178.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a `header` element with all applicable child elements
- [x] Add a `div` element with an attribute of `data-view` and a value of `form`.
- [x]  Within the form, Add a search bar and a `submit` button 
- [x] Also within the form, add a button with text content of  `My Compendium`
- [x] Below the form, create another `div ` with an attribute of `data-view` and a value of `result`
- [x] Create a placeholder Search result inside the `div` that looks just like the "Lynel" info page wireframe
- [x] Style the page to look identical to the wireframe.  
- [x] Make sure the page looks nice on both desktop and mobile, and is responsive. 
- [x] Create functionality that: 
        - listens for a `submit` event on the form, and in its callback function: 
           1. Prevent default actions from occurring
           2. Swap the data view from "form" to "result"
           3. Pull data from the "Hyrule Compendium" API
           4. Replace the placeholder data with data from the API
           5. reset the form
       - listens for a `click` event on the "Back To Search" anchor tag that: 
           1. Swaps the data view back to form
           2. resets placeholder data to what it was originally
- [x] Test search bar functionality multiple times with different categories
- [x] Remove any CSS that was unnecessary
