### ISSUE TITLE
User can save search results

### ISSUE THREAD

**Issue by nsturz** [nsturz/My-Hyrule-Compendium#3]
## ⚙️ Feature

When clicking the "add to compendium" button on a search result, user will be able to save that search result and then view it on their own personal "My Compendium" page. 

## 🖼️ Wireframes

<img width="692" alt="Screen Shot 2022-08-03 at 7 55 40 PM" src="https://user-images.githubusercontent.com/94485412/183819991-e8ec6437-fd7e-4628-a6c7-dbbbfaa635bf.png">

<img width="748" alt="Screen Shot 2022-08-09 at 10 03 36 PM" src="https://user-images.githubusercontent.com/94485412/183819999-36bbaf01-3aee-4e12-a28b-0ed978ab9fa0.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add an 'click' event listener to the “add to compendium” button, and in its callback function: 
    - [x] Put the search results’ text content into a new object (H1, H3, P, IMG)  
    - [x] Add an entryId to the object and assign it the value of data.nextEntryId
    - [x] Increment data.nextEntryId
    - [x] Prepend the object (put it at the beginning) to the entries array
    - [x] Make sure the entries along with the whole data object are set in local storage
    - [x] Make sure each new entry receives an incrementing ‘entryId’
 - [x] Add a sibling `div[data-view="entries"]` to the HTML.
 - [x] Add an empty unordered list to the `div[data-view="entries"]` element in the HTML.
 - [x] Add some dummy entries to the unordered list in the HTML and style them to match the wireframe.
 - [x] Make sure the entries list looks good on both mobile and desktop screens.
 - [x] Define a function that takes a single `entry` object and returns a DOM tree that matches one of the example 
         entries in the HTML.
  - [x] Use a loop to create a DOM tree for each new entry in the data model and append it to the page when the 
         `'DOMContentLoaded'` event is fired.
  - [x] Remove the example HTML entries once the user's entries are successfully being appended to the DOM on page load.
  - [x]  Ensure that saving a new entry also creates a new DOM tree for it and adds it to the page.
  - [x] Ensure that saving a new entry automatically shows the `'entries'` view without reloading the page.
  - [x] Ensure that refreshing the pages shows the same view as before refreshing.

*Clean Up*
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
