### ISSUE TITLE
User can add a note to a search result

### ISSUE THREAD

**Issue by nsturz** [nsturz/My-Hyrule-Compendium#5]
## ⚙️ Feature

- When clicking on an entry, user will be able to see the appropriate details, and add a note to the entry if they wish. 

## 📐 Functionality

 - User clicks on the text portion of the entry
 - Once the details load, user can click on the edit icon next to "Notes"
 -  User can type in notes about the entry, or edit the last note they made. 

## 🖼️ Wireframes

![Screen Shot 2022-08-15 at 10 31 08 PM](https://user-images.githubusercontent.com/94485412/184805120-cb256cb3-24db-4af6-b339-fc6449ded4e1.png)

![Screen Shot 2022-08-15 at 10 34 23 PM](https://user-images.githubusercontent.com/94485412/184805281-e81856f5-2750-4184-a147-74be0805200a.png)

![Screen Shot 2022-08-15 at 10 37 03 PM](https://user-images.githubusercontent.com/94485412/184805661-44d78657-4c44-4944-bf1b-d80fe5259301.png)

![Screen Shot 2022-08-15 at 10 37 45 PM](https://user-images.githubusercontent.com/94485412/184805667-5d4aa108-bba0-488f-8272-0733c8c1e5f7.png)

## ✅ Task List

- [x] update renderEntry function to add an attribute of ‘data-entry-id’ with a value of ‘entryId’
- [x] create the "edit note' modal" at the bottom of the HTML doc and ensure it looks identical to the wireframe
- [x] listen for clicks on the ul element in the "entries" view and in its callback function: 
- [x] if the event target is strictly equal to the h4 element: 
  - [x]  loop through data.entries and: 
    - [x] conditionally call one of the search-result rendering functions based on the information in data.entries and pass in the text content of the corresponding h4 element. 
    - [x] if the 'data-entry-id' of the corresponding 'li' element is strictly equal to data.entries at 'i':
        - [x] assign data.entries at 'i' to data.editing
- [x] ensure that clicking on the h4 element displays the proper search result view each time. 
- [x] listen for clicks on the “edit icon” element next to notes and in it’s callback function: 
  - [x]  viewSwap to the edit notes modal
  - [x]  change the data.view to “editing”
  - [x] ensure that the text area automatically populates with the previous text content. 
- [x] listen for a “submit” event on the notesForm element and in its callback function: 
  - [x] assign editModal.elements.notesInput.value to notesText.textContent 
  - [x] iterate through data.entries and:
    - [x] if the entryId at data.entries is strictly equal data.editing.entryId:
      - [x] assign data.entries[ i ].notes to notesText.textContent
    - [x] hide the form
    - [x] reset the form
- [x] listen for a click event on the cancel button, and in its callback function: 
  - [x]  hide the form
