### ISSUE TITLE
 User can delete an entry

### ISSUE THREAD

**Issue by nsturz** [nsturz/My-Hyrule-Compendium#7]
## ⚙️ Feature

User will be able to remove an entry from their Compendium if they wish. 

## 📐 Functionality

When clicking (or tapping) on one of their entries, on the bottom left portion of the screen there will be a "delete entry" button. When clicked, user will be asked if they are sure they want to delete the entry. When canceled, nothing happens. When confirmed, the entry is removed from their compendium and from the local storage session. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="664" alt="Screen Shot 2022-09-03 at 4 32 01 PM" src="https://user-images.githubusercontent.com/94485412/188290613-6fff93d9-a3c3-4866-8950-d86b2c17f6ff.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] In the HTML, add a sibling div to the "edit modal" form that displays a new modal.
- [x] Inside the new modal, display a message that says "Are you sure you want to delete this entry?" with a "cancel" button and a "confirm" button below.
- [x] make sure the modal looks nice on desktop and mobile.
- [x] If the user clicks "cancel", the modal disappears and shows the previous view. 
- [x] If the user clicks "confirm":
  - [x] iterate through the entries array, and if the dataId matches that of data.editing: 
    - [x] delete that entry from the array
    - [x] delete that entry from the DOM tree
    - [x] swap the view back to the "entries" view.
